dataset_params:
    dataset: ISIC2019
    data_location: /storage/sorkhei/transfer_learner/data

    train_transforms:
        Resize:
            apply: true
            height: 256
            width: 256
        CenterCrop:
            apply: false
            height: 224
            width: 224
        Normalize: true
        VerticalFlip:
            apply: false
            p: 0.5
        HorizontalFlip:
            apply: true
            p: 0.5
        RandomRotation:
            apply: false
            angle: 5
            p: 0.5
        RandomGrayscale:
            apply: false
            p: 0.2
        RandomCrop:
            apply: false
            height: 32
            width: 32
            padding: 4
            p: 0.5
        ColorJitter:
            apply: true
            brightness: 0.2
            contrast: 0.2
            saturation: 0.1
            hue: 0.1
            p: 0.8
        RandomPerspective:
            apply: false
            distortion_scale: 0.2
            p: 0.5
        RandomAffine:
            apply: false
            degrees: 5
            translate: [0.1, 0.3]
            scale: [0.1, 3.3]
            shear: 0.2
            p: 0.5
        RandomErasing:
            apply: false
            scale: [0.02, 0.33]
            ratio: [0.3, 3.3]
            value: 0
            p: 0.5
        RandomGaussianBlur:
            apply: false
            radius_min: 0.1
            radius_max: 2.0
            p: 0.2
        RandomSolarize:
            apply: false
            threshold: 128
            p: 0.2
        RandomResizedCrop:
            apply: true
            size: 224
            scale: [0.8, 1.2]
    
    val_transforms:
        Resize:
            apply: true
            height: 256
            width: 256
        CenterCrop:
            apply: true
            height: 224
            width: 224
        Normalize: true
    
    test_transforms:
        Resize:
            apply: true
            height: 256
            width: 256
        CenterCrop:
            apply: true
            height: 224
            width: 224
        Normalize: true

dataloader_params:
    trainloader:
        batch_size: 64
        num_workers: 4
        prefetch_factor: 4
        shuffle: true
        pin_memory: true
        drop_last: true
        persistent_workers: true
    valloader:
        batch_size: 64
        num_workers: 4
        prefetch_factor: 4
        shuffle: true
        pin_memory: true
        drop_last: true
        persistent_workers: true
    testloader:
        batch_size: 64
        num_workers: 4
        prefetch_factor: 4
        shuffle: false
        pin_memory: true
        drop_last: false
        persistent_workers: true

model_params:
    backbone_type: vit_base
    transformers_params:
        student:
            pretrained_type: LVD142M-SSL
            pre_img_size: 518
            patch_size: 14
            drop_path_rate: 0
            drop_path_uniform: false
            layerscale: 1.e-5
            ffn_layer: mlp
            block_chunks: 0
            num_register_tokens: 0
            interpolate_antialias: false
            interpolate_offset: 0.1
        teacher:
            momentum_teacher: 0.994
            final_momentum_teacher: 1
            warmup_teacher_temp: 0.04
            teacher_temp: 0.07
            warmup_teacher_temp_epochs: 30
    
    pretrained: true
    freeze_backbone: false
    dinov2:
        dino:
            loss_weight: 1.0
            head_n_prototypes: 65536
            head_bottleneck_dim: 256
            head_nlayers: 3
            head_hidden_dim: 2048
            koleo_loss_weight: 0.1
        ibot:
            loss_weight: 1.0
            mask_sample_probability: 0.5
            mask_ratio_min_max: [0.1, 0.5]
            separate_head: false
            head_n_prototypes: 65536
            head_bottleneck_dim: 256
            head_nlayers: 3
            head_hidden_dim: 2048
        centering: centering

optimization_params:
    default:
        optimizer:
            type: AdamW
            autoscale_lr: false
            params:
                lr: 1.e-4
                weight_decay: 1.e-5
        scheduler:
            type: [LinearWarmup, CosineAnnealingLR]
            params:
                ReduceLROnPlateau:
                    mode: max
                    factor: 0.1
                    patience: 2
                    verbose: true
                OneCycleLR:
                    anneal_strategy: linear
                    final_div_factor: 1.e-4
                MultiStepLR:
                    milestones: [7]
                    gamma: 0.1
                CosineAnnealingLR:
                    eta_min: 1.e-6
                LinearWarmup:
                    warmup_epochs: 10
                    warmup_iters: 0
                    eta_min: 1.e-8

training_params:
    model_name: debug
    epochs: 300
    freeze_last_layer_epochs: 1
    val_every: 0.5
    log_every: 25
    save_best_model: true
    knn_eval: true
    grad_clipping: 1.0
    restore_session: false
    restore_only_model: false
    use_mixed_precision: true
    save_dir: /storage/sorkhei/adapt/apla/checkpoints

system_params:
    use_all_GPUs: false
    which_GPUs: "0,1,2,3"
    use_GPU: true

log_params:
    project_name: APLA
    run_name: DEFINED_BY_MODEL_NAME


transfer_learning_params:
    pretrained_path: ""
