# the following attributes overrides/adds attributes to the __common__ config
model_params:
    adaptation:
        mode: "apla"
        params:
            partial_size: 8  # rank

optimization_params:
    default:
        optimizer:
            params:
                lr: 0.00003
        scheduler:
            type: ["LinearWarmup", "CosineAnnealingLR"]
            params:
                LinearWarmup:
                    warmup_iters: 500
